// This file is automatically generated by qtc from "login.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line login.qtpl:1
package templates

//line login.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line login.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line login.qtpl:1
func StreamHtmlHeader(qw422016 *qt422016.Writer) {
	//line login.qtpl:1
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="login form">
    <meta name="keywords" content="HTML,CSS,XML,JavaScript">
    <meta name="author" content="Joan Marc Carbó i Arnau">
    <title>IMIM Central login</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
`)
//line login.qtpl:28
}

//line login.qtpl:28
func WriteHtmlHeader(qq422016 qtio422016.Writer) {
	//line login.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:28
	StreamHtmlHeader(qw422016)
	//line login.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:28
}

//line login.qtpl:28
func HtmlHeader() string {
	//line login.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:28
	WriteHtmlHeader(qb422016)
	//line login.qtpl:28
	qs422016 := string(qb422016.B)
	//line login.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:28
	return qs422016
//line login.qtpl:28
}

//line login.qtpl:30
func StreamBodyHeader(qw422016 *qt422016.Writer) {
	//line login.qtpl:30
	qw422016.N().S(`
<body>
<div class="container">
  <div class="row" id="pwd-container">
    <div class="col-md-4"></div>
`)
//line login.qtpl:35
}

//line login.qtpl:35
func WriteBodyHeader(qq422016 qtio422016.Writer) {
	//line login.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:35
	StreamBodyHeader(qw422016)
	//line login.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:35
}

//line login.qtpl:35
func BodyHeader() string {
	//line login.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:35
	WriteBodyHeader(qb422016)
	//line login.qtpl:35
	qs422016 := string(qb422016.B)
	//line login.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:35
	return qs422016
//line login.qtpl:35
}

//line login.qtpl:37
func StreamFlashMessages(qw422016 *qt422016.Writer, messages string) {
	//line login.qtpl:37
	qw422016.N().S(`
<div>
`)
	//line login.qtpl:39
	qw422016.E().S(messages)
	//line login.qtpl:39
	qw422016.N().S(`
</div>
`)
//line login.qtpl:41
}

//line login.qtpl:41
func WriteFlashMessages(qq422016 qtio422016.Writer, messages string) {
	//line login.qtpl:41
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:41
	StreamFlashMessages(qw422016, messages)
	//line login.qtpl:41
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:41
}

//line login.qtpl:41
func FlashMessages(messages string) string {
	//line login.qtpl:41
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:41
	WriteFlashMessages(qb422016, messages)
	//line login.qtpl:41
	qs422016 := string(qb422016.B)
	//line login.qtpl:41
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:41
	return qs422016
//line login.qtpl:41
}

//line login.qtpl:43
func StreamLoginForm(qw422016 *qt422016.Writer, lt string) {
	//line login.qtpl:43
	qw422016.N().S(`
<div class="col-md-4">
	<form method="POST">
		<div class="form-group">
			<label>Username:</label>
			<input type="text" class="form-control" name="username" id="username"/>
		</div>
		<div class="form-group">
			<label>Password:</label>
			<input type="password" class="form-control" name="password" id="password"/>
		</div>
		<input type="hidden" name="lt" id="lt" value="`)
	//line login.qtpl:54
	qw422016.E().S(lt)
	//line login.qtpl:54
	qw422016.N().S(`"/>
		<button type="submit" class="btn btn-default">Login</button>
	</form>
</div>
`)
//line login.qtpl:58
}

//line login.qtpl:58
func WriteLoginForm(qq422016 qtio422016.Writer, lt string) {
	//line login.qtpl:58
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:58
	StreamLoginForm(qw422016, lt)
	//line login.qtpl:58
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:58
}

//line login.qtpl:58
func LoginForm(lt string) string {
	//line login.qtpl:58
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:58
	WriteLoginForm(qb422016, lt)
	//line login.qtpl:58
	qs422016 := string(qb422016.B)
	//line login.qtpl:58
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:58
	return qs422016
//line login.qtpl:58
}

//line login.qtpl:61
func StreamBodyFooter(qw422016 *qt422016.Writer) {
	//line login.qtpl:61
	qw422016.N().S(`
    <div class="col-md-4"></div>
  </div>
</div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
</body>
`)
//line login.qtpl:70
}

//line login.qtpl:70
func WriteBodyFooter(qq422016 qtio422016.Writer) {
	//line login.qtpl:70
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:70
	StreamBodyFooter(qw422016)
	//line login.qtpl:70
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:70
}

//line login.qtpl:70
func BodyFooter() string {
	//line login.qtpl:70
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:70
	WriteBodyFooter(qb422016)
	//line login.qtpl:70
	qs422016 := string(qb422016.B)
	//line login.qtpl:70
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:70
	return qs422016
//line login.qtpl:70
}

//line login.qtpl:72
func StreamHtmlFooter(qw422016 *qt422016.Writer) {
	//line login.qtpl:72
	qw422016.N().S(`
</html>
`)
//line login.qtpl:74
}

//line login.qtpl:74
func WriteHtmlFooter(qq422016 qtio422016.Writer) {
	//line login.qtpl:74
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:74
	StreamHtmlFooter(qw422016)
	//line login.qtpl:74
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:74
}

//line login.qtpl:74
func HtmlFooter() string {
	//line login.qtpl:74
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:74
	WriteHtmlFooter(qb422016)
	//line login.qtpl:74
	qs422016 := string(qb422016.B)
	//line login.qtpl:74
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:74
	return qs422016
//line login.qtpl:74
}
