// This file is automatically generated by qtc from "login.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line login.qtpl:1
package templates

//line login.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line login.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line login.qtpl:1
func StreamHtmlHeader(qw422016 *qt422016.Writer) {
	//line login.qtpl:1
	qw422016.N().S(`
<html>
  <head>
	<meta charset="UTF-8">
	<meta name="description" content="login form">
	<meta name="keywords" content="HTML,CSS,XML,JavaScript">
	<meta name="author" content="Joan Marc Carbó i Arnau">
  </head>
`)
//line login.qtpl:9
}

//line login.qtpl:9
func WriteHtmlHeader(qq422016 qtio422016.Writer) {
	//line login.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:9
	StreamHtmlHeader(qw422016)
	//line login.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:9
}

//line login.qtpl:9
func HtmlHeader() string {
	//line login.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:9
	WriteHtmlHeader(qb422016)
	//line login.qtpl:9
	qs422016 := string(qb422016.B)
	//line login.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:9
	return qs422016
//line login.qtpl:9
}

//line login.qtpl:11
func StreamBodyHeader(qw422016 *qt422016.Writer) {
	//line login.qtpl:11
	qw422016.N().S(`
<body>
`)
//line login.qtpl:13
}

//line login.qtpl:13
func WriteBodyHeader(qq422016 qtio422016.Writer) {
	//line login.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:13
	StreamBodyHeader(qw422016)
	//line login.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:13
}

//line login.qtpl:13
func BodyHeader() string {
	//line login.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:13
	WriteBodyHeader(qb422016)
	//line login.qtpl:13
	qs422016 := string(qb422016.B)
	//line login.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:13
	return qs422016
//line login.qtpl:13
}

//line login.qtpl:15
func StreamFlashMessages(qw422016 *qt422016.Writer, messages string) {
	//line login.qtpl:15
	qw422016.N().S(`
<div>
`)
	//line login.qtpl:17
	qw422016.E().S(messages)
	//line login.qtpl:17
	qw422016.N().S(`
</div>
`)
//line login.qtpl:19
}

//line login.qtpl:19
func WriteFlashMessages(qq422016 qtio422016.Writer, messages string) {
	//line login.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:19
	StreamFlashMessages(qw422016, messages)
	//line login.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:19
}

//line login.qtpl:19
func FlashMessages(messages string) string {
	//line login.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:19
	WriteFlashMessages(qb422016, messages)
	//line login.qtpl:19
	qs422016 := string(qb422016.B)
	//line login.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:19
	return qs422016
//line login.qtpl:19
}

//line login.qtpl:21
func StreamLoginForm(qw422016 *qt422016.Writer, lt string) {
	//line login.qtpl:21
	qw422016.N().S(`
<form method="POST">
	<label>Username:</label>
	<input type="text" name="username" id="username"/>
	<label>Password:</label>
	<input type="text" name="password" id="password"/>
	<input type="hidden" name="lt" id="lt" value="`)
	//line login.qtpl:27
	qw422016.E().S(lt)
	//line login.qtpl:27
	qw422016.N().S(`"/>
	<input type="submit" name="submit" id="submit" value="Login"/>
</form>
`)
//line login.qtpl:30
}

//line login.qtpl:30
func WriteLoginForm(qq422016 qtio422016.Writer, lt string) {
	//line login.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:30
	StreamLoginForm(qw422016, lt)
	//line login.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:30
}

//line login.qtpl:30
func LoginForm(lt string) string {
	//line login.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:30
	WriteLoginForm(qb422016, lt)
	//line login.qtpl:30
	qs422016 := string(qb422016.B)
	//line login.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:30
	return qs422016
//line login.qtpl:30
}

//line login.qtpl:33
func StreamBodyFooter(qw422016 *qt422016.Writer) {
	//line login.qtpl:33
	qw422016.N().S(`
</body>
`)
//line login.qtpl:35
}

//line login.qtpl:35
func WriteBodyFooter(qq422016 qtio422016.Writer) {
	//line login.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:35
	StreamBodyFooter(qw422016)
	//line login.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:35
}

//line login.qtpl:35
func BodyFooter() string {
	//line login.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:35
	WriteBodyFooter(qb422016)
	//line login.qtpl:35
	qs422016 := string(qb422016.B)
	//line login.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:35
	return qs422016
//line login.qtpl:35
}

//line login.qtpl:37
func StreamHtmlFooter(qw422016 *qt422016.Writer) {
	//line login.qtpl:37
	qw422016.N().S(`
</html>
`)
//line login.qtpl:39
}

//line login.qtpl:39
func WriteHtmlFooter(qq422016 qtio422016.Writer) {
	//line login.qtpl:39
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:39
	StreamHtmlFooter(qw422016)
	//line login.qtpl:39
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:39
}

//line login.qtpl:39
func HtmlFooter() string {
	//line login.qtpl:39
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:39
	WriteHtmlFooter(qb422016)
	//line login.qtpl:39
	qs422016 := string(qb422016.B)
	//line login.qtpl:39
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:39
	return qs422016
//line login.qtpl:39
}
