// This file is automatically generated by qtc from "login.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line login.qtpl:1
package templates

//line login.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line login.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line login.qtpl:1
func StreamHtmlHeader(qw422016 *qt422016.Writer) {
	//line login.qtpl:1
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="login form">
    <meta name="keywords" content="HTML,CSS,XML,JavaScript">
    <meta name="author" content="Joan Marc Carbó i Arnau">
    <title>IMIM Central login</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
`)
//line login.qtpl:28
}

//line login.qtpl:28
func WriteHtmlHeader(qq422016 qtio422016.Writer) {
	//line login.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:28
	StreamHtmlHeader(qw422016)
	//line login.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:28
}

//line login.qtpl:28
func HtmlHeader() string {
	//line login.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:28
	WriteHtmlHeader(qb422016)
	//line login.qtpl:28
	qs422016 := string(qb422016.B)
	//line login.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:28
	return qs422016
//line login.qtpl:28
}

//line login.qtpl:30
func StreamBodyHeader(qw422016 *qt422016.Writer) {
	//line login.qtpl:30
	qw422016.N().S(`
<body>
<div class="container">
`)
//line login.qtpl:33
}

//line login.qtpl:33
func WriteBodyHeader(qq422016 qtio422016.Writer) {
	//line login.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:33
	StreamBodyHeader(qw422016)
	//line login.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:33
}

//line login.qtpl:33
func BodyHeader() string {
	//line login.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:33
	WriteBodyHeader(qb422016)
	//line login.qtpl:33
	qs422016 := string(qb422016.B)
	//line login.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:33
	return qs422016
//line login.qtpl:33
}

//line login.qtpl:35
func StreamFlashMessages(qw422016 *qt422016.Writer, messages string) {
	//line login.qtpl:35
	qw422016.N().S(`
<div>
`)
	//line login.qtpl:37
	qw422016.E().S(messages)
	//line login.qtpl:37
	qw422016.N().S(`
</div>
`)
//line login.qtpl:39
}

//line login.qtpl:39
func WriteFlashMessages(qq422016 qtio422016.Writer, messages string) {
	//line login.qtpl:39
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:39
	StreamFlashMessages(qw422016, messages)
	//line login.qtpl:39
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:39
}

//line login.qtpl:39
func FlashMessages(messages string) string {
	//line login.qtpl:39
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:39
	WriteFlashMessages(qb422016, messages)
	//line login.qtpl:39
	qs422016 := string(qb422016.B)
	//line login.qtpl:39
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:39
	return qs422016
//line login.qtpl:39
}

//line login.qtpl:41
func StreamLoginForm(qw422016 *qt422016.Writer, lt string) {
	//line login.qtpl:41
	qw422016.N().S(`
<form method="POST">
	<div class="form-group">
		<label>Username:</label>
		<input type="text" class="form-control" name="username" id="username"/>
	</div>
	<div class="form-group">
		<label>Password:</label>
		<input type="text" class="form-control" name="password" id="password"/>
	</div>
	<input type="hidden" name="lt" id="lt" value="`)
	//line login.qtpl:51
	qw422016.E().S(lt)
	//line login.qtpl:51
	qw422016.N().S(`"/>
	<button type="submit" class="btn btn-default">Login</button>
</form>
`)
//line login.qtpl:54
}

//line login.qtpl:54
func WriteLoginForm(qq422016 qtio422016.Writer, lt string) {
	//line login.qtpl:54
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:54
	StreamLoginForm(qw422016, lt)
	//line login.qtpl:54
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:54
}

//line login.qtpl:54
func LoginForm(lt string) string {
	//line login.qtpl:54
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:54
	WriteLoginForm(qb422016, lt)
	//line login.qtpl:54
	qs422016 := string(qb422016.B)
	//line login.qtpl:54
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:54
	return qs422016
//line login.qtpl:54
}

//line login.qtpl:57
func StreamBodyFooter(qw422016 *qt422016.Writer) {
	//line login.qtpl:57
	qw422016.N().S(`
</div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
</body>
`)
//line login.qtpl:64
}

//line login.qtpl:64
func WriteBodyFooter(qq422016 qtio422016.Writer) {
	//line login.qtpl:64
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:64
	StreamBodyFooter(qw422016)
	//line login.qtpl:64
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:64
}

//line login.qtpl:64
func BodyFooter() string {
	//line login.qtpl:64
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:64
	WriteBodyFooter(qb422016)
	//line login.qtpl:64
	qs422016 := string(qb422016.B)
	//line login.qtpl:64
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:64
	return qs422016
//line login.qtpl:64
}

//line login.qtpl:66
func StreamHtmlFooter(qw422016 *qt422016.Writer) {
	//line login.qtpl:66
	qw422016.N().S(`
</html>
`)
//line login.qtpl:68
}

//line login.qtpl:68
func WriteHtmlFooter(qq422016 qtio422016.Writer) {
	//line login.qtpl:68
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line login.qtpl:68
	StreamHtmlFooter(qw422016)
	//line login.qtpl:68
	qt422016.ReleaseWriter(qw422016)
//line login.qtpl:68
}

//line login.qtpl:68
func HtmlFooter() string {
	//line login.qtpl:68
	qb422016 := qt422016.AcquireByteBuffer()
	//line login.qtpl:68
	WriteHtmlFooter(qb422016)
	//line login.qtpl:68
	qs422016 := string(qb422016.B)
	//line login.qtpl:68
	qt422016.ReleaseByteBuffer(qb422016)
	//line login.qtpl:68
	return qs422016
//line login.qtpl:68
}
