// This file is automatically generated by qtc from "redirect.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line redirect.qtpl:1
package templates

//line redirect.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line redirect.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line redirect.qtpl:1
func StreamRedirect(qw422016 *qt422016.Writer, url string) {
	//line redirect.qtpl:1
	qw422016.N().S(`
<html>
    <head>
        <title>Yale Central Authentication Service</title>
        <script>
            window.location.href="`)
	//line redirect.qtpl:6
	qw422016.E().S(url)
	//line redirect.qtpl:6
	qw422016.N().S(`";
       </script>
    </head>
    <body>
        <noscript>
            <p>CAS login successful.</p>
            <p>  Click <a href="`)
	//line redirect.qtpl:12
	qw422016.E().S(url)
	//line redirect.qtpl:12
	qw422016.N().S(`" >here</a>
            to access the service you requested.<br />  </p>
        </noscript>
    </body>
 </html>
`)
//line redirect.qtpl:17
}

//line redirect.qtpl:17
func WriteRedirect(qq422016 qtio422016.Writer, url string) {
	//line redirect.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line redirect.qtpl:17
	StreamRedirect(qw422016, url)
	//line redirect.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line redirect.qtpl:17
}

//line redirect.qtpl:17
func Redirect(url string) string {
	//line redirect.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
	//line redirect.qtpl:17
	WriteRedirect(qb422016, url)
	//line redirect.qtpl:17
	qs422016 := string(qb422016.B)
	//line redirect.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
	//line redirect.qtpl:17
	return qs422016
//line redirect.qtpl:17
}
